# https://github.com/actions/create-release
# https://github.com/vitejs/vite/blob/main/.github/workflows/release-tag.yml

name: Release

on:
  push:
    tags:
      - '@videojs-player/*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get package name for tag
        id: tag
        run: |
          # `%@*` truncates @ and version number from the right side.
          # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
          # https://www.edwardthomson.com/blog/github_actions_15_sharing_data_between_steps.html
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-setting-an-output-parameter
          pkgName=${GITHUB_REF_NAME%@*}
          echo "::set-output name=pkgName::$pkgName"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/surmon-china/videojs-player/blob/${{ github.ref_name }}/packages/${{ steps.tag.outputs.pkgName }}/CHANGELOG.md) for details.
